using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared._Moffstation.ReadyManifest; /// LP edit
using Robust.Shared.Utility; /// LP edit

namespace Content.Client._Moffstation.ReadyManifest.UI;

[GenerateTypedNameReferences]
public sealed partial class ReadyManifestEntry : GridContainer
{
    /// LP edit start
    private static readonly Color EmptyColor = Color.Gray; /// color yellow > gray
    private static readonly Color MediumColor = Color.White;
    private static readonly Color HighColor = Color.Yellow;
    /// LP start end

    public ReadyManifestEntry()
    {
        RobustXamlLoader.Load(this);
    }
    public ReadyManifestEntry(
        JobPrototype job,
        ReadyManifestJobCount jobCount, /// LP edit
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSystem)
    {
        RobustXamlLoader.Load(this);
        EntryTitle.SetMessage(job.LocalizedName + ":");

        var jobIcon = prototypeManager.Index(job.Icon);
        EntryIcon.Texture = spriteSystem.Frame0(jobIcon.Icon);

        /// LP edit start
        // ReadyCount.SetMessage(jobCount.ToString(), null, jobCount > 0 ? TakenColor : EmptyColor);

        var emptyHighPriority = jobCount.High == 0;
        var emptyMediumPriority = jobCount.Medium == 0;
        var message = new FormattedMessage();

        message.PushColor(emptyHighPriority ? EmptyColor : HighColor);
        message.AddText(jobCount.High.ToString());
        message.Pop();

        message.AddText(" (");

        message.PushColor(emptyMediumPriority ? EmptyColor : MediumColor);
        message.AddText(jobCount.Medium.ToString());
        message.Pop();

        message.AddText(")");

        ReadyCount.SetMessage(message);
        /// LP edit end
    }
}
