using Content.Shared.Access.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FunkyStation.NanoChat;

[GenerateTypedNameReferences]
public sealed partial class CreateGroupChatPopup : DefaultWindow
{
    private const int MaxFullNameLength = 30;
    private const int MaxJobTitleLength = 30;
    public event Action<string>? OnGroupCreated;

    public CreateGroupChatPopup()
    {
        RobustXamlLoader.Load(this);

        ContentsContainer.Margin = new Thickness(3);

        // Button handlers
        CancelButton.OnPressed += _ => Close();
        CreateButton.OnPressed += _ => CreateGroup();

        // Input validation
        GroupNameInput.OnTextEntered += _ => CreateGroup();

        GroupNameInput.OnTextChanged += args =>
        {
            if (args.Text.Length > MaxFullNameLength)
                GroupNameInput.Text = args.Text[..MaxFullNameLength];
            ValidateInputs();
        };
    }

    private void ValidateInputs()
    {
        var isValid = !string.IsNullOrWhiteSpace(GroupNameInput.Text);
        CreateButton.Disabled = !isValid;
    }

    private void CreateGroup()
    {
        if (CreateButton.Disabled)
            return;

        var name = GroupNameInput.Text.Trim();
        OnGroupCreated?.Invoke(name);
        Close();
    }

    public void ClearInputs()
    {
        GroupNameInput.Text = string.Empty;
        ValidateInputs();
    }
}
