- type: loadout
  id: LPHOSPanties
  equipment:
    underwear: LPPHOSPanties

- type: loadout
  id: LPPHOSSummer
  equipment:
    jumpsuit: ClothingUniformJumpsuitHOSSummer

- type: loadout
  id: LPPHOSFormalskirt
  equipment:
    jumpsuit: LPPClothingUniformJumpskirtHoSFormalSkirt

- type: loadout
  id: LPPHOSCloakFur
  equipment:
    neck: ClothingNeckCloakHosFur
