ignored_paths: # Игнорирует указанные пути до папок/файлов
- "Resources/Locale/ru-RU/corvax"
- "Resources/Locale/ru-RU/datasets"
- "Resources/Locale/ru-RU/_ADT"
- "Resources/Locale/ru-RU/_AruMoon"
- "Resources/Locale/ru-RU/_CorvaxGoob"
- "Resources/Locale/ru-RU/_CorvaxNext"
- "Resources/Locale/ru-RU/_LP"
- "Resources/Locale/ru-RU/_Orion"
- "Resources/Locale/ru-RU/_Wega"
- "Resources/Locale/ru-RU/_White"
- "Resources/Locale/ru-RU/_WL"
- "Resources/Locale/ru-RU/_GoobStation/NTR/document.ftl"
ignored_untranslated_paths: # Игнорирует предупреждения в указанных путях до папок/файлов
- "Resources/Locale/ru-RU/robust-toolbox/input.ftl"
- "Resources/Locale/ru-RU/atmos/gases.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/toolshed-commands.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/commands.ftl"
- "Resources/Locale/ru-RU/speech/speech-chatsan.ftl"
- "Resources/Locale/ru-RU/magic/spells-actions.ftl"
- "Resources/Locale/ru-RU/accent"
- "Resources/Locale/ru-RU/commands"
- "Resources/Locale/ru-RU/actions/commands"
- "Resources/Locale/ru-RU/robust-toolbox/replays.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/uploadfolder.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/dev-window.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/physics/grid_merging.ftl"
- "Resources/Locale/ru-RU/robust-toolbox/controls.ftl"
- "Resources/Locale/ru-RU/actions/actions/actions-commands.ftl"
- "Resources/Locale/ru-RU/administration/commands"
- "Resources/Locale/ru-RU/administration/ui/tabs/adminbus-tab/blueprints.ftl"
- "Resources/Locale/ru-RU/administration/ui/ban-list.ftl"
- "Resources/Locale/ru-RU/cvar"
- "Resources/Locale/ru-RU/bql/bql-select.ftl"
- "Resources/Locale/ru-RU/atmos/commands.ftl"
- "Resources/Locale/ru-RU/objectives/commands"
- "Resources/Locale/ru-RU/players/play-time/play-time-commands.ftl"
- "Resources/Locale/ru-RU/voting/vote-commands.ftl"
- "Resources/Locale/ru-RU/verbs/invoke-verb-command.ftl"
- "Resources/Locale/ru-RU/verbs/list-verbs-command.ftl"
- "Resources/Locale/ru-RU/shuttles/commands.ftl"
- "Resources/Locale/ru-RU/power/commands.ftl"
- "Resources/Locale/ru-RU/nuke/nuke-command.ftl"
- "Resources/Locale/ru-RU/procedural/command.ftl"
- "Resources/Locale/ru-RU/npc/npc-debug.ftl"
- "Resources/Locale/ru-RU/job/role-ban-command.ftl"
- "Resources/Locale/ru-RU/damage/damage-command.ftl"
- "Resources/Locale/ru-RU/game-ticking/set-game-preset-command.ftl"
- "Resources/Locale/ru-RU/chat/chat-repo.ftl"
- "Resources/Locale/ru-RU/feedbackpopup/feedbackpopup.ftl"
- "Resources/Locale/ru-RU/ss14-ru/prototypes/_lp/entities/objects/weapons/bombs/C4Low.ftl"
- "Resources/Locale/ru-RU/shell.ftl"
- "Resources/Locale/ru-RU/lobby/lobby-state-background.ftl"
ignored_variable_mismatch_paths:
- "Resources/Locale/ru-RU/stack/stacks.ftl"
- "Resources/Locale/ru-RU/bed/cryostorage/cryogenic-storage.ftl"
- "Resources/Locale/ru-RU/game-ticking/game-ticker.ftl"
- "Resources/Locale/ru-RU/spray-painter/spray-painter.ftl"
- "Resources/Locale/ru-RU/chat/managers/chat-manager.ftl"
- "Resources/Locale/ru-RU/botany/components/plant-holder-component.ftl"
